"""
db_query_tool.py
-----------------
Smolagents tool for deterministic access to agricultural data stored
in PostgreSQL (Maui/Pandino project).
The tool does NOT interpret natural language: it expects a parsed structure
prepared by the agent, and executes the correct SQL wrapper.
"""

import logging
from typing import Any, Dict, List, Optional

from smolagents import Tool
from dotenv import load_dotenv

from database_pg import (
    get_associations_by_district,
    get_associations_by_product,
    get_product_in_district,
    get_association_details,
    get_association_with_products,
)

load_dotenv()


class DatabaseQueryTool(Tool):
    """
    Deterministic SmolAgents tool for querying agricultural data.
    The tool expects a structured 'parsed' argument specifying which
    database query to run (product, district, both, or association name).
    It does not attempt any natural language interpretation.
    """

    name = "db_query"
    description = (
        "Execute deterministic SQL queries on the agricultural dataset. "
        "This tool does NOT interpret the natural-language question; it uses "
        "the structured 'parsed' object generated by the agent to select the "
        "appropriate database query."
    )
    output_type = "object"

    inputs = {
        "question": {
            "type": "string",
            "description": "Original user question (not interpreted by the tool)."
        },
        "parsed": {
            "type": "object",
            "description": (
                "Parsed structure returned by the agent. Must contain values such as: "
                "'district', 'product', 'association'. "
                "The tool selects the correct SQL query using this structure."
            )
        }
    }

    def forward(
        self,
        question: str,
        parsed: Dict[str, Optional[str]],
    ) -> Dict[str, Any]:
        """
        Executes the correct SQL wrapper based on the structured 'parsed' content.

        :param question: User question (unused by the tool, only logged).
        :param parsed: Dictionary that must contain at least one of:
                       - product
                       - district
                       - association
        :return: Dictionary with query results and metadata.
        """

        logging.info(f"[db_query_tool] Received parsed={parsed}")

        product = parsed.get("product")
        district = parsed.get("district")
        association = parsed.get("association")

        try:
            # === DECISIONE DELLA QUERY DA ESEGUIRE ===

            # 1) Prodotto + Distretto
            if product and district:
                results = get_product_in_district(product, district)
                query_type = "product_in_district"

            # 2) Solo prodotto
            elif product:
                results = get_associations_by_product(product)
                query_type = "product_only"

            # 3) Solo distretto
            elif district:
                results = get_associations_by_district(district)
                query_type = "district_only"

            # 4) Solo associazione
            elif association:
                # Step 1 — Cerca associazioni che matchano il nome
                base_results = get_association_details(association)

                # Step 2 — Arricchisci ciascuna associazione con i suoi prodotti
                results = []
                for assoc in base_results:
                    assoc_id = assoc.get("id")
                    if assoc_id is not None:
                        enriched = get_association_with_products(assoc_id)
                        if enriched:
                            results.append(enriched)
                    else:
                        # fallback: restituiamo almeno i dati base
                        results.append(assoc)

                query_type = "association_details_with_products"


            else:
                return {
                    "results": [],
                    "error": (
                        "Parsed input does not contain 'product', "
                        "'district' or 'association'."
                    )
                }

            # === RISPOSTA FINALE ===
            return {
                "results": results,
                "query_type": query_type,
                "parsed": parsed,
            }

        except Exception as e:
            logging.exception("[db_query_tool] Database query execution failed")
            return {
                "results": [],
                "error": str(e),
            }
