"""
INVARIANT A0
The test suite contains a permanent test, driven by the `ast` module of the
Python standard library, which walks the whole repository (excluding `venv/`)
and asserts:

  violations(A1) union violations(A2) union violations(A5a) union
  violations(A5b) union violations(A5c)  is a subset of  BASELINE union
  DECLARED_EXCEPTIONS

where BASELINE is an explicit, machine-readable registry of the call sites
that are known to violate an invariant and are scheduled to be fixed by a
later axis, and DECLARED_EXCEPTIONS is a separate, explicit registry of the
call sites that are permitted to violate an invariant permanently, each with
a stated reason.

The test fails if a violation appears that is in neither registry. The test
also fails if a BASELINE entry no longer corresponds to an existing violation,
so that a fixed site cannot be left in the registry.

BASELINE and DECLARED_EXCEPTIONS must be two distinct registries. A site is
never moved from BASELINE to DECLARED_EXCEPTIONS as a way of closing an axis.

This module holds BASELINE: sites known to violate an invariant today and
scheduled to be fixed by a later axis of the logging-standardization effort.
Generated by running the scanner in tests/test_logging_invariants.py against
the current tree; no line numbers are recorded because line numbers are not
stable across commits.

Key: (invariant, posix_relative_path, enclosing_function_name)
Value: number of violations recorded at that key.
"""

BASELINE: dict[tuple[str, str, str], int] = {
    ("A1a", "datachat/tools/aggregate_tool.py", "forward"): 3,
    ("A1a", "datachat/tools/correlation_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/describe_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/filter_rows_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/missing_values_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/plot_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/row_count_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/sample_rows_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/top_rows_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/trend_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/unique_values_tool.py", "forward"): 2,
    ("A1a", "infrastructure/ai.py", "asr_response"): 1,
    ("A1a", "infrastructure/ai.py", "choose_emb_model"): 5,
    ("A1a", "infrastructure/ai.py", "choose_llm"): 3,
    ("A1a", "infrastructure/ai.py", "describe_image"): 2,
    ("A1a", "infrastructure/ai.py", "extract_text_from_image_with_usage"): 2,
    ("A1a", "infrastructure/database_pg.py", "add_cost"): 1,
    ("A1a", "infrastructure/database_pg.py", "add_prompt"): 3,
    ("A1a", "infrastructure/database_pg.py", "add_user"): 3,
    ("A1a", "infrastructure/database_pg.py", "delete_cost"): 1,
    ("A1a", "infrastructure/database_pg.py", "delete_prompt"): 2,
    ("A1a", "infrastructure/database_pg.py", "delete_rag_file"): 2,
    ("A1a", "infrastructure/database_pg.py", "edit_tokens"): 3,
    ("A1a", "infrastructure/database_pg.py", "get_feedback_for_admin"): 1,
    ("A1a", "infrastructure/database_pg.py", "get_feedback_stats"): 1,
    ("A1a", "infrastructure/database_pg.py", "get_prompt_from_db"): 3,
    ("A1a", "infrastructure/database_pg.py", "get_user_by_username"): 4,
    ("A1a", "infrastructure/database_pg.py", "get_user_tokens"): 2,
    ("A1a", "infrastructure/database_pg.py", "insert_rag_file"): 1,
    ("A1a", "infrastructure/database_pg.py", "pgvector_maui_id_exists"): 1,
    ("A1a", "infrastructure/database_pg.py", "remove_user"): 3,
    ("A1a", "infrastructure/database_pg.py", "table_exists"): 1,
    ("A1a", "infrastructure/database_pg.py", "update_cost"): 1,
    ("A1a", "infrastructure/database_pg.py", "validate_api_key"): 2,
    ("A1a", "infrastructure/prompt_utils.py", "load_prompt"): 2,
    ("A1a", "infrastructure/prompt_utils.py", "render_prompt"): 2,
    ("A1a", "infrastructure/retriever_tool.py", "forward"): 3,
    ("A1a", "routes/datachat.py", "dataChat"): 5,
    ("A1a", "routes/datachat.py", "startChat"): 1,
    ("A1a", "routes/documents.py", "compare_docs"): 1,
    ("A1a", "routes/multimodal.py", "asr_parse"): 1,
    ("A1a", "routes/multimodal.py", "audio_form_compile"): 1,
    ("A1a", "routes/rag.py", "agentchat"): 6,
    ("A1a", "routes/rag.py", "completion_handler"): 1,
    ("A1a", "routes/users.py", "editTokens"): 1,
    ("A1a", "routes/users.py", "feedback_handler"): 1,
    ("A1a", "services/audio_form_service.py", "audioFormCompilation"): 2,
    ("A1a", "services/audio_form_service.py", "audioFormPromptBuild"): 1,
    ("A1a", "services/completion_service.py", "complete_chat"): 4,
    ("A1a", "services/prompt_service.py", "reply_to_prompt"): 1,
    ("A1a", "services/rag_ingestion_service.py", "process_rag_file"): 1,
    ("A1a", "services/retrieval_service.py", "retrieve_from_collection"): 3,
    ("A1b-binding", "datachat/tools/aggregate_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/correlation_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/describe_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/filter_rows_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/missing_values_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/plot_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/row_count_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/sample_rows_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/top_rows_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/trend_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/unique_values_tool.py", "MODULE"): 1,
    ("A1b-binding", "infrastructure/ai.py", "MODULE"): 1,
    ("A1b-binding", "infrastructure/database_pg.py", "MODULE"): 1,
    ("A1b-binding", "infrastructure/prompt_utils.py", "MODULE"): 1,
    ("A1b-binding", "infrastructure/retriever_tool.py", "MODULE"): 1,
    ("A1b-binding", "routes/datachat.py", "MODULE"): 1,
    ("A1b-binding", "routes/documents.py", "MODULE"): 1,
    ("A1b-binding", "routes/multimodal.py", "MODULE"): 1,
    ("A1b-binding", "routes/rag.py", "MODULE"): 1,
    ("A1b-binding", "routes/users.py", "MODULE"): 1,
    ("A1b-binding", "services/audio_form_service.py", "MODULE"): 1,
    ("A1b-binding", "services/completion_service.py", "MODULE"): 1,
    ("A1b-binding", "services/prompt_service.py", "MODULE"): 1,
    ("A1b-binding", "services/rag_ingestion_service.py", "MODULE"): 1,
    ("A1b-binding", "services/retrieval_service.py", "MODULE"): 1,
    ("A1b-binding", "utils/agent_logging.py", "MODULE"): 1,
    ("A1b-binding", "utils/logging_config.py", "MODULE"): 1,
    ("A1b-chained", "utils/agent_logging.py", "log_runresult"): 1,
    ("A2", "datachat/tools/aggregate_tool.py", "forward"): 3,
    ("A2", "datachat/tools/correlation_tool.py", "forward"): 2,
    ("A2", "datachat/tools/describe_tool.py", "forward"): 2,
    ("A2", "datachat/tools/filter_rows_tool.py", "forward"): 2,
    ("A2", "datachat/tools/missing_values_tool.py", "forward"): 2,
    ("A2", "datachat/tools/plot_tool.py", "forward"): 2,
    ("A2", "datachat/tools/row_count_tool.py", "forward"): 2,
    ("A2", "datachat/tools/sample_rows_tool.py", "forward"): 2,
    ("A2", "datachat/tools/top_rows_tool.py", "forward"): 2,
    ("A2", "datachat/tools/trend_tool.py", "forward"): 2,
    ("A2", "datachat/tools/unique_values_tool.py", "forward"): 2,
    ("A2", "infrastructure/retriever_tool.py", "forward"): 3,
    ("A2", "routes/datachat.py", "dataChat"): 5,
    ("A2", "routes/documents.py", "compare_docs"): 1,
    ("A2", "routes/rag.py", "agentchat"): 5,
    ("A2", "routes/users.py", "feedback_handler"): 1,
    ("A2", "services/retrieval_service.py", "retrieve_from_collection"): 3,
    ("A2", "utils/agent_logging.py", "log_runresult"): 1,
    ("A5a", "main.py", "MODULE"): 1,
    ("A5b", "infrastructure/database_pg.py", "list_users"): 1,
    ("A5b", "infrastructure/database_pg.py", "print_stored_keys"): 2,
    ("A5c", "main.py", "MODULE"): 1,
}
