"""
INVARIANT A0
The test suite contains a permanent test, driven by the `ast` module of the
Python standard library, which walks the whole repository (excluding `venv/`)
and asserts:

  violations(A1) union violations(A2) union violations(A5a) union
  violations(A5b) union violations(A5c)  is a subset of  BASELINE union
  DECLARED_EXCEPTIONS

where BASELINE is an explicit, machine-readable registry of the call sites
that are known to violate an invariant and are scheduled to be fixed by a
later axis, and DECLARED_EXCEPTIONS is a separate, explicit registry of the
call sites that are permitted to violate an invariant permanently, each with
a stated reason.

The test fails if a violation appears that is in neither registry. The test
also fails if a BASELINE entry no longer corresponds to an existing violation,
so that a fixed site cannot be left in the registry.

BASELINE and DECLARED_EXCEPTIONS must be two distinct registries. A site is
never moved from BASELINE to DECLARED_EXCEPTIONS as a way of closing an axis.

This module holds DECLARED_EXCEPTIONS: sites permitted to violate an
invariant permanently, each with a stated reason. A site here is never
scheduled to be fixed by moving it out of this registry; it belongs here for
as long as the code it names exists. Generated by running the scanner in
tests/test_logging_invariants.py against the current tree; no line numbers
are recorded because line numbers are not stable across commits.

Key: (invariant, posix_relative_path, enclosing_function_name)
Value: (number of violations recorded at that key, reason)
"""

DECLARED_EXCEPTIONS: dict[tuple[str, str, str], tuple[int, str]] = {
    ("A1b-binding", "tests/test_logging_config.py", "MODULE"): (
        1,
        "This test module deliberately exercises the bootstrap's handler and "
        "isolation behaviour against arbitrary, non-module logger names and "
        "the chained getLogger(...).<level>() form, so it has no "
        "module-level logger = logging.getLogger(__name__) binding by "
        "design.",
    ),
    ("A1b-chained", "tests/test_logging_config.py", "_capture"): (
        1,
        "This test module deliberately calls "
        "logging.getLogger(<arbitrary or parametrized name>).warning(...) "
        "in chained form to exercise the logging bootstrap's own "
        "handler-attachment and isolation behaviour; using a non-module "
        "logger via the chained call is the point of the test, not a "
        "production emission awaiting migration.",
    ),
    ("A1b-chained", "tests/test_logging_config.py", "boom"): (
        1,
        "This test module deliberately calls "
        "logging.getLogger(<arbitrary or parametrized name>).warning(...) "
        "in chained form to exercise the logging bootstrap's own "
        "handler-attachment and isolation behaviour; using a non-module "
        "logger via the chained call is the point of the test, not a "
        "production emission awaiting migration.",
    ),
    ("A1b-chained", "tests/test_logging_config.py", "kaboom"): (
        1,
        "This test module deliberately calls "
        "logging.getLogger(<arbitrary or parametrized name>).warning(...) "
        "in chained form to exercise the logging bootstrap's own "
        "handler-attachment and isolation behaviour; using a non-module "
        "logger via the chained call is the point of the test, not a "
        "production emission awaiting migration.",
    ),
    ("A1b-chained", "tests/test_logging_config.py", "ping"): (
        1,
        "This test module deliberately calls "
        "logging.getLogger(<arbitrary or parametrized name>).warning(...) "
        "in chained form to exercise the logging bootstrap's own "
        "handler-attachment and isolation behaviour; using a non-module "
        "logger via the chained call is the point of the test, not a "
        "production emission awaiting migration.",
    ),
    ("A1b-chained", "tests/test_logging_config.py", "slowping"): (
        1,
        "This test module deliberately calls "
        "logging.getLogger(<arbitrary or parametrized name>).warning(...) "
        "in chained form to exercise the logging bootstrap's own "
        "handler-attachment and isolation behaviour; using a non-module "
        "logger via the chained call is the point of the test, not a "
        "production emission awaiting migration.",
    ),
    (
        "A1b-chained",
        "tests/test_logging_config.py",
        "test_explicit_context_fields_are_not_overwritten",
    ): (
        1,
        "This test module deliberately calls "
        "logging.getLogger(<arbitrary or parametrized name>).warning(...) "
        "in chained form to exercise the logging bootstrap's own "
        "handler-attachment and isolation behaviour; using a non-module "
        "logger via the chained call is the point of the test, not a "
        "production emission awaiting migration.",
    ),
    ("A1b-chained", "tests/test_logging_config.py", "worker"): (
        1,
        "This test module deliberately calls "
        "logging.getLogger(<arbitrary or parametrized name>).warning(...) "
        "in chained form to exercise the logging bootstrap's own "
        "handler-attachment and isolation behaviour; using a non-module "
        "logger via the chained call is the point of the test, not a "
        "production emission awaiting migration.",
    ),
    ("A5c", "infrastructure/database_pg.py", "init_db"): (
        2,
        "These print() calls report progress of a command run by hand from "
        "a terminal; stdout output is the function's purpose, not a side "
        "effect, and init_db() has no caller anywhere else in the tree.",
    ),
    ("A5c", "infrastructure/database_pg.py", "list_users"): (
        4,
        "This CLI-only function prints a tabular listing of users to "
        "stdout by design; list_users() has no caller anywhere else in the "
        "tree, so its stdout output is the function's purpose, not a side "
        "effect.",
    ),
    ("A5c", "infrastructure/database_pg.py", "print_help"): (
        9,
        "This function prints the CLI's help text; stdout output is the "
        "function's entire purpose and print_help() has no caller anywhere "
        "else in the tree.",
    ),
    ("A5c", "infrastructure/database_pg.py", "print_stored_keys"): (
        4,
        "This CLI-only function prints stored-key diagnostics to stdout by "
        "design; print_stored_keys() has no caller anywhere else in the "
        "tree, so its stdout output is the function's purpose, not a side "
        "effect.",
    ),
}
