"""
INVARIANT A0
The test suite contains a permanent test, driven by the `ast` module of the
Python standard library, which walks the whole repository (excluding `venv/`)
and asserts:

  violations(A1) union violations(A2) union violations(A5a) union
  violations(A5b) union violations(A5c)  is a subset of  BASELINE union
  DECLARED_EXCEPTIONS

where BASELINE is an explicit, machine-readable registry of the call sites
that are known to violate an invariant and are scheduled to be fixed by a
later axis, and DECLARED_EXCEPTIONS is a separate, explicit registry of the
call sites that are permitted to violate an invariant permanently, each with
a stated reason.

The test fails if a violation appears that is in neither registry. The test
also fails if a BASELINE entry no longer corresponds to an existing violation,
so that a fixed site cannot be left in the registry.

BASELINE and DECLARED_EXCEPTIONS must be two distinct registries. A site is
never moved from BASELINE to DECLARED_EXCEPTIONS as a way of closing an axis.

This module holds BASELINE: sites known to violate an invariant today and
scheduled to be fixed by a later axis of the logging-standardization effort.
Generated by running the scanner in tests/test_logging_invariants.py against
the current tree; no line numbers are recorded because line numbers are not
stable across commits.

Key: (invariant, posix_relative_path, enclosing_function_name)
Value: number of violations recorded at that key.
"""

BASELINE: dict[tuple[str, str, str], int] = {
    ("A5a", "main.py", "MODULE"): 1,
    ("A5b", "infrastructure/database_pg.py", "list_users"): 1,
    ("A5b", "infrastructure/database_pg.py", "print_stored_keys"): 2,
    ("A5c", "main.py", "MODULE"): 1,
}
