"""
INVARIANT A0
The test suite contains a permanent test, driven by the `ast` module of the
Python standard library, which walks the whole repository (excluding `venv/`)
and asserts:

  violations(A1) union violations(A2) union violations(A5a) union
  violations(A5b) union violations(A5c)  is a subset of  BASELINE union
  DECLARED_EXCEPTIONS

where BASELINE is an explicit, machine-readable registry of the call sites
that are known to violate an invariant and are scheduled to be fixed by a
later axis, and DECLARED_EXCEPTIONS is a separate, explicit registry of the
call sites that are permitted to violate an invariant permanently, each with
a stated reason.

The test fails if a violation appears that is in neither registry. The test
also fails if a BASELINE entry no longer corresponds to an existing violation,
so that a fixed site cannot be left in the registry.

BASELINE and DECLARED_EXCEPTIONS must be two distinct registries. A site is
never moved from BASELINE to DECLARED_EXCEPTIONS as a way of closing an axis.

This module holds BASELINE: sites known to violate an invariant today and
scheduled to be fixed by a later axis of the logging-standardization effort.
Generated by running the scanner in tests/test_logging_invariants.py against
the current tree; no line numbers are recorded because line numbers are not
stable across commits.

Key: (invariant, posix_relative_path, enclosing_function_name)
Value: number of violations recorded at that key.
"""

BASELINE: dict[tuple[str, str, str], int] = {
    ("A1a", "datachat/tools/aggregate_tool.py", "forward"): 3,
    ("A1a", "datachat/tools/correlation_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/describe_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/filter_rows_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/missing_values_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/plot_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/row_count_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/sample_rows_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/top_rows_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/trend_tool.py", "forward"): 2,
    ("A1a", "datachat/tools/unique_values_tool.py", "forward"): 2,
    ("A1a", "routes/datachat.py", "dataChat"): 5,
    ("A1a", "routes/datachat.py", "startChat"): 1,
    ("A1a", "routes/documents.py", "compare_docs"): 1,
    ("A1a", "routes/multimodal.py", "asr_parse"): 1,
    ("A1a", "routes/multimodal.py", "audio_form_compile"): 1,
    ("A1a", "routes/rag.py", "agentchat"): 6,
    ("A1a", "routes/rag.py", "completion_handler"): 1,
    ("A1a", "routes/users.py", "editTokens"): 1,
    ("A1a", "routes/users.py", "feedback_handler"): 1,
    ("A1b-binding", "datachat/tools/aggregate_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/correlation_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/describe_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/filter_rows_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/missing_values_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/plot_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/row_count_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/sample_rows_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/top_rows_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/trend_tool.py", "MODULE"): 1,
    ("A1b-binding", "datachat/tools/unique_values_tool.py", "MODULE"): 1,
    ("A1b-binding", "routes/datachat.py", "MODULE"): 1,
    ("A1b-binding", "routes/documents.py", "MODULE"): 1,
    ("A1b-binding", "routes/multimodal.py", "MODULE"): 1,
    ("A1b-binding", "routes/rag.py", "MODULE"): 1,
    ("A1b-binding", "routes/users.py", "MODULE"): 1,
    ("A1b-binding", "utils/agent_logging.py", "MODULE"): 1,
    ("A1b-binding", "utils/logging_config.py", "MODULE"): 1,
    ("A1b-chained", "utils/agent_logging.py", "log_runresult"): 1,
    ("A2", "datachat/tools/aggregate_tool.py", "forward"): 3,
    ("A2", "datachat/tools/correlation_tool.py", "forward"): 2,
    ("A2", "datachat/tools/describe_tool.py", "forward"): 2,
    ("A2", "datachat/tools/filter_rows_tool.py", "forward"): 2,
    ("A2", "datachat/tools/missing_values_tool.py", "forward"): 2,
    ("A2", "datachat/tools/plot_tool.py", "forward"): 2,
    ("A2", "datachat/tools/row_count_tool.py", "forward"): 2,
    ("A2", "datachat/tools/sample_rows_tool.py", "forward"): 2,
    ("A2", "datachat/tools/top_rows_tool.py", "forward"): 2,
    ("A2", "datachat/tools/trend_tool.py", "forward"): 2,
    ("A2", "datachat/tools/unique_values_tool.py", "forward"): 2,
    ("A2", "infrastructure/retriever_tool.py", "forward"): 3,
    ("A2", "routes/datachat.py", "dataChat"): 5,
    ("A2", "routes/documents.py", "compare_docs"): 1,
    ("A2", "routes/rag.py", "agentchat"): 5,
    ("A2", "routes/users.py", "feedback_handler"): 1,
    ("A2", "services/retrieval_service.py", "retrieve_from_collection"): 3,
    ("A2", "utils/agent_logging.py", "log_runresult"): 1,
    ("A5a", "main.py", "MODULE"): 1,
    ("A5b", "infrastructure/database_pg.py", "list_users"): 1,
    ("A5b", "infrastructure/database_pg.py", "print_stored_keys"): 2,
    ("A5c", "main.py", "MODULE"): 1,
}
