import logging
import textwrap
from typing import Any, TypedDict, Union

from infrastructure.ai import choose_llm
from infrastructure.prompt_utils import load_prompt, render_prompt

logger = logging.getLogger(__name__)


class TokenUsage(TypedDict):
    """
    Represents token usage metadata returned by the LLM provider,
    when available through response metadata. Populated only on a
    successful LLM invocation; zero values indicate the provider did
    not report usage.
    """

    input_tokens: int
    output_tokens: int


class AudioFormServiceResult(TypedDict):
    """
    Represents the full result returned by the audio form compilation service.

    :field content: The raw string response generated by the LLM. Contains a
        JSON object whose schema mirrors the form schema passed in the request.
        Must not be parsed or validated by the service — schema varies per call.
    :field token_usage: Input and output token counts reported by the LLM
        provider for the invocation.
    """

    content: str
    token_usage: TokenUsage


def audioFormPromptBuild(
    formSchemaExampleData: dict[str, Any],
    formSchemaName: str,
    formSchemaChoices: list[dict[str, Any]],
    transcribedAudio: str,
    language: str = "ITA",
) -> dict[str, str]:
    """
    Builds a pair of prompts (system and user) to instruct an LLM to populate
    a JSON form based on a given schema, example data, available choices, and
    a transcribed audio input.

    :param formSchemaExampleData: Dictionary with an example of the form
        compiled with empty/default values.
    :param formSchemaName: Name of the form, used in the prompts.
    :param formSchemaChoices: List of dictionaries representing selectable
        choices for choice-based fields.
    :param transcribedAudio: Transcribed user audio input, from which field
        values will be extracted.
    :param language: ISO 3166-1 alpha-3 language code for the reply language.
        Defaults to "ITA".
    :return: A dictionary with 'systemprompt' and 'userprompt' keys.
    :raises ValueError: If any required input is missing.
    """
    if not formSchemaExampleData or not formSchemaName or not transcribedAudio:
        raise ValueError(
            "Missing one or more required inputs for building audio form prompts"
        )

    fieldTypes = formSchemaExampleData["fieldTypes"]
    fieldDescriptions = formSchemaExampleData["fieldDescriptions"]

    logger.info("Building audio form prompts for schema: %s", formSchemaName)

    language_instruction = (
        f"Please answer using the official language of the country corresponding "
        f"to the following ISO 3166-1 alpha-3 code: {language}. "
        f"If you can't match the language, please answer in English."
    )

    default_audio_form_system = textwrap.dedent("""\
        You are an assistant specialized in extracting data from audio transcriptions.
        Respond EXCLUSIVELY in valid JSON format.
        Do not add comments, explanations, or additional text.
    """)

    default_audio_form_user = textwrap.dedent("""\
        INPUT DATA:
        Form schema name: {formSchemaName}
        Available options: {formSchemaChoices}
        Output template and field types: {fieldTypes}
        Field descriptions: {fieldDescriptions}
        Audio transcription: {transcribedAudio}
        
        INSTRUCTIONS:
        Fill out the JSON template using ONLY information from the transcription.
        RULES PER FIELD:
        - boolean: true/false based on the transcription
        - multiplechoice: array of values from "Available options". If a mentioned option is not present and if "other" exists among the Available options, include "other"
        - singlechoice: array of values from "Available options". If a mentioned option is not present and if "other" exists among the Available options, include "other"
        - date: YYYY-MM-DD format
        - text/string: text extracted from the transcription
        - range/number: numeric value
        OUTPUT: Compiled JSON following the provided template.
    """)

    system_base_template = load_prompt(
        "audio_form_system", default_text=default_audio_form_system
    )
    system_base = render_prompt(system_base_template)

    user_base_template = load_prompt(
        "audio_form_user", default_text=default_audio_form_user
    )
    user_base = render_prompt(
        user_base_template,
        formSchemaName=formSchemaName,
        formSchemaChoices=formSchemaChoices,
        fieldTypes=fieldTypes,
        fieldDescriptions=fieldDescriptions,
        transcribedAudio=transcribedAudio,
    )

    system = f"{language_instruction}\n\n{system_base.strip()}"
    user = f"{language_instruction}\n\n{user_base.strip()}"

    return {"systemprompt": system, "userprompt": user}


def audioFormCompilation(
    userprompt: str,
    systemprompt: str,
    llm_type: str,
    model: str,
    api_key: str | None = None,
) -> AudioFormServiceResult:
    """
    Sends a user/system prompt pair to a selected LLM and returns the generated
    content together with token usage metadata.

    :param userprompt: Prompt containing audio-derived user input instructions.
    :param systemprompt: Prompt defining rules and expected structure of response.
    :param llm_type: Type/provider of the language model (e.g. 'OpenAI', 'Anthropic').
    :param model: Specific model name to invoke.
    :param api_key: Optional API key override. Falls back to environment variables
        if not provided.
    :return: AudioFormServiceResult with the raw LLM response string and token usage.
    :raises ValueError: If any required parameter is missing.
    :raises RuntimeError: If the LLM invocation fails.
    """
    if not all([userprompt, systemprompt, llm_type, model]):
        raise ValueError(
            "Missing one or more required parameters for audioFormCompilation"
        )

    logger.info(
        "Invoking audio form compilation with model=%s (provider=%s)",
        model,
        llm_type,
    )

    messages = [
        {"role": "system", "content": systemprompt},
        {"role": "user", "content": userprompt},
    ]

    try:
        llm = choose_llm(llm_type, model, temperature=0, api_key=api_key)
        resp = llm.invoke(messages)

        token_usage = getattr(resp, "response_metadata", {}).get("token_usage", {})
        token_in = token_usage.get("prompt_tokens", 0)
        token_out = token_usage.get("completion_tokens", 0)

        content = resp.content if isinstance(resp.content, str) else str(resp.content)

        return {
            "content": content,
            "token_usage": {"input_tokens": token_in, "output_tokens": token_out},
        }

    except Exception as e:
        logger.exception("Error in audio form compilation")
        raise RuntimeError(f"Audio form compilation failed: {str(e)}")
