import logging
import textwrap
import time
from dataclasses import dataclass
from typing import Any, TypedDict

from infrastructure.vector_store import VectorStore

from infrastructure.ai import choose_llm
from infrastructure.prompt_utils import load_prompt, render_prompt
from utils.embedding_operation_context import OPERATION_QUERY, embedding_operation
from utils.operational_event import build_operational_event

logger = logging.getLogger(__name__)


class TokenUsage(TypedDict):
    """
    Represents token usage metadata returned by the LLM provider,
    when available through response metadata. Populated only on a
    successful LLM invocation; zero values indicate the provider did
    not report usage.
    """

    input_tokens: int
    output_tokens: int


class CompletionServiceResult(TypedDict):
    """
    Represents the full result returned by the completion service.

    :field answer: The text response generated by the LLM, or a fixed
        fallback message when no relevant context was found.
    :field vectors: The list of vector store entries used as context for
        the answer. Empty when no relevant vectors were found.
    :field token_usage: Input and output token counts reported by the
        LLM provider for the invocation.
    :field is_no_info: True when the answer matches a known "no information"
        phrase, indicating the model could not find relevant content.
    """

    answer: str
    vectors: list[dict]
    token_usage: TokenUsage
    is_no_info: bool


@dataclass
class CompletionRequest:
    """
    Represents the input contract for a chat completion request.

    :field username: The username of the requester, used for token usage logging.
    :field info: Additional background information to supplement the vector context.
    :field chat: Alternating list of assistant/user messages representing the
        conversation history. The last element is treated as the current question.
    :field language: ISO 3166-1 alpha-3 language code used to instruct the model
        on the reply language. Defaults to "ENG".
    """

    username: str
    info: list[str]
    chat: list[str]
    language: str = "ENG"


def complete_chat(
    req: CompletionRequest,
    store: VectorStore,
    llm_type: str,
    model: str,
    language: str = "ENG",
    api_key: str | None = None,
    top_k: int = 5,
    min_sim: float = 0.5,
) -> CompletionServiceResult:
    """
    Perform a RAG-based chat completion using a vector store for contextual retrieval.

    The function retrieves relevant vectors for the last message in the chat history,
    assembles a structured prompt with context and conversation history, invokes the
    selected LLM, and returns the answer together with token usage and source vectors.

    :param req: CompletionRequest containing the username, chat history, background
        info, and language preference.
    :param store: VectorStore instance used to retrieve semantically similar content.
    :param llm_type: LLM provider identifier (e.g. "OpenAI", "Anthropic").
    :param model: Model name/version to invoke.
    :param language: ISO 3166-1 alpha-3 language code for the reply language.
        Defaults to "ENG".
    :param api_key: Optional API key override. Falls back to environment variables if not provided.
    :param top_k: Number of top similar vectors to retrieve. Defaults to 5.
    :param min_sim: Minimum similarity threshold for returned vectors. Defaults to 0.5.
    :return: CompletionServiceResult with the answer, source vectors, token usage,
        and a flag indicating whether the model reported no relevant information.
    :raises RuntimeError: If the chat history is empty or invalid, if vector
        retrieval fails, or if the LLM invocation fails.
    """
    if not req.chat or not isinstance(req.chat, list):
        raise RuntimeError("No chat history provided.")

    question = req.chat[-1].strip()
    if not question:
        raise RuntimeError("No question found in chat history.")

    logger.info("event=completion_started llm_type=%s model=%s", llm_type, model)
    logger.info("event=completion_question_received")

    vectors: list[dict[str, Any]] = []

    try:
        # The scope covers the retrieval call and nothing else: it names the
        # embedding this question produces, and must not still be in effect
        # when the LLM below runs. Restoration is the context manager's, on
        # both the success and the exception path.
        with embedding_operation(OPERATION_QUERY):
            vectors = store.find_similar_vectors(
                text=question, top_k=top_k, min_similarity=min_sim
            )
    except Exception as e:
        # Only the exception class name is persisted: str(e) may embed
        # the query or vector-store connection detail.
        message, extra = build_operational_event(
            event="completion_retrieval_failed",
            error_type=type(e).__name__,
        )
        logger.warning(message, extra=extra)
        raise RuntimeError(f"Vector retrieval failed: {str(e)}")

    # Emitted for every successful retrieval, including vector_count=0,
    # and therefore before the no-context early return below: degraded-success
    # reconstruction depends on this record existing. This is the authoritative
    # structured emission at this seam and replaces the former runtime
    # completion_retrieval_result log, so one real fact yields one LogRecord.
    message, extra = build_operational_event(
        event="completion_retrieval_completed",
        details={
            "vector_count": len(vectors),
            "top_k": top_k,
            "min_sim": min_sim,
            "info_present": bool(req.info),
        },
    )
    logger.info(message, extra=extra)

    if not req.info and not vectors:
        return {
            "answer": "No relevant information available.",
            "vectors": [],
            "token_usage": {"input_tokens": 0, "output_tokens": 0},
            "is_no_info": True,
        }

    language_instruction = (
        f"Please answer using the official language of the country corresponding to the following ISO 3166-1 alpha-3 code: {language}. "
        f"If you can't match the language, please answer in English."
    )

    default_complete_chat_prompt = textwrap.dedent("""\
            You are Dino, an assistant who helps users by answering questions concisely.
            You will receive information divided by
            BACKGROUND INFORMATION:
            Here you will find the context of previous reply
            RELEVANT CONTENT
            Here you will find context to reply to CURRENT QUESTION
            PREVIUOS CONVERSATION CONTEXT
            you will find here the chat history
            CURRENT QUESTION
            the question that you should reply following the important instruction below

            IMPORTANT INSTRUCTIONS:
            1. You MUST ALWAYS check the provided context and information to answer questions
            2. You MUST ONLY use information from the provided context to answer
            3. You MUST NOT make up or infer information not present in the context
            4. You MUST NEVER say 'I have no information about this' if there is ANY relevant information in the context
            5. If you find ANY relevant information in the context, use it to provide a partial answer
            6. Only say 'I have no information about this' if the context contains ABSOLUTELY NOTHING relevant to the question
    """)

    base_prompt_template = load_prompt(
        "complete_chat_system", default_text=default_complete_chat_prompt
    )

    base_prompt = render_prompt(base_prompt_template)

    full_prompt = f"{language_instruction}\n\n{base_prompt.strip()}"

    messages = [{"role": "system", "content": full_prompt}]

    context = ""
    if vectors:
        context += "RELEVANT CONTEXT:\n----------------"
    for vec in vectors:
        context += "\n" + vec["metadata"]["text"]

    if context:
        messages.append(
            {
                "role": "user",
                "content": "Here is the context you MUST use to answer questions:\n\n"
                + context,
            }
        )
        messages.append(
            {
                "role": "assistant",
                "content": "I have received the context and will ONLY use this information to answer questions. I will not make up or infer information not present in this context.",
            }
        )

    if len(req.chat) > 1:
        messages.append(
            {
                "role": "user",
                "content": "PREVIUOS CONVERSATION CONTEXT:\n-------------------------",
            }
        )
        for i in range(0, len(req.chat) - 1, 2):
            messages.append(
                {"role": "assistant", "content": f"ASSISTANT: {req.chat[i]}"}
            )
            messages.append({"role": "user", "content": f"USER: {req.chat[i+1]}"})

    messages.append(
        {
            "role": "user",
            "content": (
                f"CURRENT QUESTION:\n"
                f"----------------\n"
                f"{req.chat[-1]}\n\n"
                "IMPORTANT INSTRUCTIONS:\n"
                "1. Search through ALL the context provided above\n"
                "2. Find ANY relevant information that relates to this question\n"
                "3. If you find ANY relevant information, use it to answer\n"
                "4. Only say 'I have no information about this' if you find ABSOLUTELY NOTHING relevant\n"
                "5. Your answer must ONLY use information from the provided context"
            ),
        }
    )

    try:
        llm = choose_llm(llm_type, model, api_key=api_key)

        # Duration boundary: the timer brackets llm.invoke() and
        # nothing else. choose_llm(), response parsing and the is_no_info
        # classifier stay outside it, so duration_ms keeps meaning "how long
        # did the provider take" rather than drifting with payload shape.
        provider_call_started = time.perf_counter()
        try:
            resp = llm.invoke(messages)
            provider_duration_ms = round(
                (time.perf_counter() - provider_call_started) * 1000
            )
        except Exception as e:
            # Emitted only once the provider attempt has actually
            # started: a choose_llm() failure never reaches here. One record
            # serves both consumers — stderr keeps the traceback, the
            # Operational snapshot keeps only the bounded fields. This
            # replaces the former runtime completion_failed line.
            message, extra = build_operational_event(
                event="completion_provider_failed",
                provider=llm_type,
                model=model,
                duration_ms=round(
                    (time.perf_counter() - provider_call_started) * 1000
                ),
                error_type=type(e).__name__,
            )
            logger.exception(message, extra=extra)
            raise

        answer = resp.content

        token_usage = getattr(resp, "response_metadata", {}).get("token_usage", {})
        token_in = token_usage.get("prompt_tokens", 0)
        token_out = token_usage.get("completion_tokens", 0)

        answer_text = answer if isinstance(answer, str) else str(answer)

        no_info_phrases = [
            "Non ho informazioni",
            "I have no information",
            "I don't have any information",
            "No information available",
        ]
        is_no_info = any(
            phrase.lower() in answer_text.lower() for phrase in no_info_phrases
        )

        # Carries the final classifier verdict, which is why it is
        # emitted after parsing rather than at the timer stop. No token counts
        # (Usage owns those) and no answer content.
        message, extra = build_operational_event(
            event="completion_provider_completed",
            provider=llm_type,
            model=model,
            duration_ms=provider_duration_ms,
            details={"is_no_info": is_no_info},
        )
        logger.info(message, extra=extra)

        return {
            "answer": answer_text,
            "vectors": vectors,
            "token_usage": {"input_tokens": token_in, "output_tokens": token_out},
            "is_no_info": is_no_info,
        }

    except Exception as e:
        raise RuntimeError(f"Chat completion failed: {str(e)}")
